// src/components/ui/PhIcon.jsx
import React from "react";
import {
  Robot,
  Scales,
  Gavel,
  FileText,
  FileMagnifyingGlass,
  FileDoc,
  PencilSimpleLine,
  CalendarCheck,
  CalendarDots,
  FolderOpen,
  Sparkle,
  ArrowUp,
  Paperclip,
  Microphone,
  MicrophoneSlash,
  X,
  MagnifyingGlass,
  House,
  GearSix,
  ChatCircleDots,
  FolderSimple,
  Article,
  GitDiff,
  Plus,
  PlusSquare,
  PlusCircle,
  Clock,
  ClockCountdown,
  CalendarBlank,
  Shield,
  ShieldCheck,
  ShieldStar,
  Lightning,
  Lock,
  Eye,
  EyeSlash,
  Users,
  Buildings,
  Briefcase,
  Student,
  Rocket,
  Check,
  CheckCircle,
  Star,
  ArrowRight,
  ArrowLeft,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  DotsThree,
  DotsThreeVertical,
  SignOut,
  Moon,
  Sun,
  Warning,
  WarningCircle,
  Info,
  Trash,
  TrashSimple,
  Copy,
  Download,
  Upload,
  UploadSimple,
  Phone,
  PhoneDisconnect,
  Envelope,
  EnvelopeSimple,
  MapPin,
  Globe,
  LinkedinLogo,
  User,
  UserCircle,
  Crown,
  CreditCard,
  Receipt,
  Tag,
  Newspaper,
  BookOpen,
  BookBookmark,
  Books,
  Handshake,
  PresentationChart,
  ChartBar,
  Target,
  Lightbulb,
  Percent,
  Play,
  Pause,
  Stop,
  PhoneCall,
  SpeakerHigh,
  SpeakerSlash,
  Pencil,
  FlowArrow,
  TreeStructure,
  Quotes,
  ChatTeardrop,
  ChatText,
  ShareNetwork,
  ArrowsClockwise,
  Bookmark,
  Timer,
  QrCode,
  Notification,
  Bell,
  Camera,
  ArrowsOut,
  FunnelSimple,
  List,
  SealCheck,
  Image,
  SquaresFour,
  FolderStar,
  Folder,
  Sliders,
  ClockClockwise,
  ArrowCounterClockwise,
  Circle,
  Table,
  GridFour,
  Bank,
  Money,
  Chat,
  TrendUp,
  UserPlus,
  HouseLine,
  Mountains,
  Heart,
  UserCheck,
  Copyright,
  CodeBlock,
  Headset,
  Wrench,
  Hammer,
  IdentificationCard,
} from "@phosphor-icons/react";

const ICON_MAP = {
  // AI / Chat tools
  smart_toy: Robot,
  balance: Scales,
  gavel: Gavel,
  shield: ShieldCheck,
  summarize: FileMagnifyingGlass,
  edit_document: PencilSimpleLine,
  compare: GitDiff,
  event: CalendarCheck,
  event_available: CalendarCheck,
  calendar_month: CalendarDots,
  calendar_today: CalendarBlank,
  calendar_clock: ClockCountdown,
  folder_open: FolderOpen,
  folder_off: Folder,
  folder_special: FolderStar,
  auto_awesome: Sparkle,
  article: Article,
  text_snippet: FileText,
  picture_as_pdf: FileDoc,
  description: FileText,
  // Navigation
  home: House,
  settings: GearSix,
  edit_square: ChatCircleDots,
  search: MagnifyingGlass,
  search_off: MagnifyingGlass,
  menu: List,
  // Actions
  close: X,
  stop: Stop,
  attach_file: Paperclip,
  mic: Microphone,
  arrow_upward: ArrowUp,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  add: Plus,
  add_circle: PlusCircle,
  delete: Trash,
  delete_forever: TrashSimple,
  content_copy: Copy,
  download: Download,
  upload: Upload,
  upload_file: UploadSimple,
  cloud_upload: Upload,
  share: ShareNetwork,
  refresh: ArrowsClockwise,
  edit: Pencil,
  fullscreen: ArrowsOut,
  filter_alt: FunnelSimple,
  // General
  person: User,
  account_circle: UserCircle,
  school: Student,
  check: Check,
  check_circle: CheckCircle,
  verified: SealCheck,
  star: Star,
  bookmark: Bookmark,
  expand_more: CaretDown,
  chevron_right: CaretRight,
  chevron_left: CaretLeft,
  more_vert: DotsThreeVertical,
  logout: SignOut,
  dark_mode: Moon,
  light_mode: Sun,
  warning: Warning,
  error: WarningCircle,
  error_outline: WarningCircle,
  info: Info,
  lock: Lock,
  mail_lock: EnvelopeSimple,
  visibility: Eye,
  visibility_off: EyeSlash,
  bolt: Lightning,
  rocket_launch: Rocket,
  groups: Users,
  phone: Phone,
  call_end: PhoneDisconnect,
  email: Envelope,
  location_on: MapPin,
  language: Globe,
  public: Globe,
  workspace_premium: Crown,
  credit_card: CreditCard,
  lightbulb: Lightbulb,
  // Content
  format_quote: Quotes,
  forum: ChatTeardrop,
  chat_paste_go: ChatText,
  library_books: Books,
  menu_book: BookOpen,
  chrome_reader_mode: BookBookmark,
  history: ClockClockwise,
  schedule: Clock,
  timer: Timer,
  qr_code_2: QrCode,
  notifications_active: Bell,
  photo_camera: Camera,
  preview: Eye,
  analytics: ChartBar,
  account_tree: TreeStructure,
  temp_preferences_custom: Sliders,
  // Additional
  undo: ArrowCounterClockwise,
  circle: Circle,
  mic_off: MicrophoneSlash,
  expand_less: CaretUp,
  table_chart: Table,
  grid_on: GridFour,
  account_balance: Bank,
  payments: Money,
  chat: Chat,
  apps: SquaresFour,
  business: Buildings,
  badge: IdentificationCard,
  more_horiz: DotsThree,
  storefront: Buildings,
  apartment: Buildings,
  build: Wrench,
  construction: Hammer,
  trending_up: TrendUp,
  person_add: UserPlus,
  landscape: Mountains,
  volunteer_activism: Heart,
  how_to_reg: UserCheck,
  copyright: Copyright,
  code: CodeBlock,
  support_agent: Headset,
};

const DEFAULT_SIZE = 16;

export default function PhIcon({ name, size = DEFAULT_SIZE, className = "", weight = "regular" }) {
  const IconComponent = ICON_MAP[name] || Sparkle;
  return <IconComponent size={size} className={className} weight={weight} />;
}
